version: '3.7'
services:
  config_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: config_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: Password@123
    ports:
      - 27017:27017
    networks:
      - data_mover
    volumes:
      - ./database/init_config_db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume-1:/data/db
  
  schedular_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: schedular_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: Password@123
    ports:
      - 27018:27017
    networks:
      - data_mover
    volumes:
      - ./database/init_schedular_db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume-2:/data/db

networks:
  data_mover:
    driver: bridge